### ISSUE TITLE
enable feed which could be integrated elsewhere

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [cgm616/0rc#28] opened 2016-03-14 06:23 UTC
user wants:

> I wonder if we could add a feed in this, so we can see when people reply to us :)

Normally when someone mentions you, the text line will get blue colored. So, that should give one already a good info when looking at the chat page.

But, I assume it's about getting the info (that someone replied) faster.

The feed (of replies from chat) could be integrated into ZeroHello, or some kind of RSS thinggy ?

**Comment by cgm616** [comment] 2016-03-19 15:42
Duplicate of #12

**Closed as completed by cgm616** 2016-03-19 15:42 UTC
